import { z } from "zod";

import type { FieldErrors } from "@/lib/result";

/**
 * Shared validation building blocks.
 *
 * Every schema in this folder mirrors a database constraint. The database stays
 * the enforcement point; these exist so a PA gets a message next to the field
 * instead of a 400 from PostgREST.
 */

/** A whole number at or above zero - units, counts, display order. */
export const naturalNumber = (label: string) =>
  z.coerce
    .number({ error: `${label} must be a number.` })
    .int(`${label} must be a whole number.`)
    .min(0, `${label} cannot be negative.`);

/** A percentage keyed in by hand, 0-100 with two decimals (numeric(5,2)). */
export const percentage = (label: string) =>
  z.coerce
    .number({ error: `${label} must be a number.` })
    .min(0, `${label} cannot be below 0.`)
    .max(100, `${label} cannot be above 100.`)
    .multipleOf(0.01, `${label} can have at most 2 decimal places.`);

/** Trimmed, non-empty text. */
export const requiredText = (label: string, max = 200) =>
  z
    .string({ error: `${label} is required.` })
    .trim()
    .min(1, `${label} is required.`)
    .max(max, `${label} must be ${max} characters or fewer.`);

/** An ISO `YYYY-MM-DD` date, matching a Postgres `date` column. */
export const isoDate = (label: string) =>
  z.iso.date(`${label} must be a valid date.`);

/**
 * An id from a `uuid` column.
 *
 * `z.guid()` rather than `z.uuid()` on purpose: `z.uuid()` also enforces the
 * RFC 9562 version and variant bits, which Postgres does not. Every id here is
 * generated by `gen_random_uuid()` (v4, so it would pass either way) and is
 * opaque to us, but a hand-written id like
 * `00000000-0000-0000-0000-000000000001` is perfectly valid to the database and
 * must not be rejected by the layer in front of it.
 */
export const uuid = (label: string) => z.guid(`${label} must be a valid id.`);

/**
 * Flattens a ZodError into the `FieldErrors` shape Server Actions return.
 * Nested paths are joined with a dot so a form can look them up by name.
 */
export function toFieldErrors(error: z.ZodError): FieldErrors {
  const fieldErrors: FieldErrors = {};

  for (const issue of error.issues) {
    const key = issue.path.length > 0 ? issue.path.join(".") : "_form";
    (fieldErrors[key] ??= []).push(issue.message);
  }

  return fieldErrors;
}
